console.log(1 > 2);
console.log(5 < 10);
console.log(3 >= 3);
console.log(5 <= 4);
console.log(5 == 4);
console.log('Gildeone' != 'Gildeone');
console.log(3 === '3');
console.log(4 === 4);
console.log(typeof (1 > 2));
console.log(typeof (5 < 10));
console.log(typeof (3 >= 3));
console.log(typeof (5 <= 4));